Add cterm support
kaicataldo/material.vim pull request #41
Opened 2020-03-20 21:26 UTC by gko

`vim` in macOS (8.1 anyway) doesn't support `termguicolors` (even in iterm2).

This is a draft of proposal on how to add a support for cterm colors here.
I've generated the closest colors with help of this https://gist.github.com/mhulse/b11e568260fb8c3aa2a8
bash script

2020-04-01 16:40 UTC, kaicataldo requested changes
Thanks for working on this! I’m supportive of adding this :+1:

Sorry to ask this again, but do you mind including a screenshot of each theme? It allows others to provide input without having to download the branch manually and is nice for posterity.

2020-04-01 16:40 UTC, kaicataldo commented on colors/material.vim
> +                    \ "#292D3E",
Can we use the colors defined in the colors map so that these colors are defined in one place?

2020-04-04 04:33 UTC, kaicataldo commented on colors/material.vim
> +                    \ "#292D3E",
Once this gets fixed this we should be able to land this :)

2020-04-21 05:17 UTC, gko commented
I accidentally deleted the fork and couldn't restore it, so I recreated the PR here: #45

2020-04-21 05:17 UTC, closed without merging